# Generated by Django 4.2.1 on 2023-07-03 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la categoria')),
                ('nombreCategoria', models.CharField(max_length=30, null=True, verbose_name='Nombre de las categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.AutoField(primary_key=True, serialize=False)),
                ('fEntrega', models.DateField()),
                ('fCompra', models.DateField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False, verbose_name='id de la Pregunta')),
                ('nombrePregunta', models.CharField(max_length=100, null=True, verbose_name='Nombre de la Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Rol')),
                ('nombreRol', models.CharField(max_length=80, null=True, verbose_name='Nombre del Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rutUsuario', models.IntegerField(max_length=12, primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefonoUsuario', models.IntegerField()),
                ('correoUsuario', models.CharField(max_length=80)),
                ('fechaUsuario', models.DateField()),
                ('claveUsuario', models.CharField(max_length=35)),
                ('respuestaUsuario', models.CharField(max_length=100)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.pregunta')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=300)),
                ('marca', models.CharField(max_length=30)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('fotoProducto', models.ImageField(upload_to='massimple')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.usuario'),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
                ('estado', models.CharField(max_length=25)),
                ('fecha_compra', models.DateField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto')),
                ('run_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.usuario')),
            ],
        ),
    ]
